### ISSUE TITLE
No IP Allocated Error

### ISSUE THREAD

**Issue by incrypto32** [lakinduakash/linux-wifi-hotspot#209]
**Describe the bug**

**To Reproduce**
1. Create a wifi hostpot
2. Connect from another device to the hotspot

**Expected behavior**
Expected to get connected

**Screenshots**
![photo_2021-11-08_10-11-17](https://user-images.githubusercontent.com/44740264/140685408-7ae5a14c-e617-4770-9dc9-bb0157e1b596.jpg)

**Desktop (please complete the following information):**
 - OS: Manjaro
 

**Additional context**
Seems like an issue with my laptop only. Works fine when I checked from another system

**Comment by lakinduakash** [comment]
This is strange. Can you run the `wihotspot` command in terminal and post the output. Also try connecting another device and check whether working (ip get assigned). DHCP must work fine.

**Comment by incrypto32** [comment]
Here @lakinduakash here is the screenshot
![2021-11-08_11-50](https://user-images.githubusercontent.com/44740264/140693518-d337da88-5f1c-4e6d-be60-87649c43735a.png)

**Comment by incrypto32** [comment]
@lakinduakash I also tried from another phone and it didn't work too Same issue.

**Comment by lakinduakash** [comment]
I can suggest as a temporary fix, assigning an IP to the device from the network setting. I think your DHCP server not working properly. This is the first time this issue came up.

**Comment by arimgibson** [comment]
I'm experiencing the same issue, Fedora 35 built from source at https://github.com/lakinduakash/linux-wifi-hotspot/commit/04dae5083320fed55d4622af64bb1b1de0785a5b. Currently troubleshooting and will edit this post as I learn some new information. So far, I'm getting errors running `create_ap` but the GUI will start just fine and let me connect via static IP as you suggested. I don't have internet when connecting with static IP, but I think that's my fault for assigning the wrong IP.

**Comment by arimgibson** [comment]
Okay, I might have your fix @incrypto32! At least this worked for me, and I have no clue why. A simple removal (or purge, depending on your package manager) of `dnsmasq` and `iptables` did it for me. I'm wondering if by chance our OS's ship with a version of those two software that is initialized with some config that just doesn't work for `linux-wifi-hotspot`. I don't think I had any software that would've installed those otherwise; just the built-in wifi hotspot feature in my Fedora. Anyways, good luck!

**Comment by lakinduakash** [comment]
Thanks for helping troubleshoot. Even I had no way to reproduce it

**Comment by Luciogi** [comment]
@arimgibson Thanks for Fix
On Fedora 35, removal of iptables-nft fixes ip issue, also Allow internet access to connected devices

**Comment by huzhifeng** [comment]
I also encountered the problem of not able to get IP address on Fedora 36, it's caused by firewall-cmd.
My solution: `sudo firewall-cmd --zone=FedoraWorkstation --add-port=67/udp`

**Comment by VenomousSteam81** [comment]
Same. But I took @huzhifeng command and modified it to be `sudo firewall-cmd --permanent --zone=public --add-port=67/udp`.

**Comment by laur89** [comment]
If you don't have any other service listening on some ports, then switching the firewalld off for the hotspot duration may also be an option:
`sudo systemctl stop firewalld` assuming you're using systemd. Or can also brute force by `sudo killall firewalld`

**Comment by adnanalbeda** [comment]
I found that If I configure network on mobile to use `static ip` instead of `dhcp`, it works, and I don't have to do anything about firewall.

**Comment by Vic-41148** [comment]
## A fix for create_ap clients not getting an IP on Arch Linux (nftables blocking DHCP):

add these to your /etc/nftables.conf:

### In your 'input' chain (Allows DHCP/DNS):

```
iifname "ap*" udp dport 67 accept comment "create_ap DHCP"
iifname "ap*" udp dport 53 accept comment "create_ap DNS"
iifname "ap*" tcp dport 53 accept comment "create_ap DNS"
```

### In your 'forward' chain (Allows internet access):

```
iifname "ap*" accept comment "create_ap forward in"
oifname "ap*" accept comment "create_ap forward out"
```
## !!If you skip this, DHCP will work, but a default-deny forward chain will still block internet access.

Use ap* instead of ap0 so your rules don't break if create_ap crashes and spawns ap1 on the next run.



Root Cause: Arch's default-deny nftables blocks the AP interface. create_ap doesn't add rules for it, so you have to manually allow it in two places.


Debug: tcpdump shows DHCPDISCOVER packets arriving, but dnsmasq logs nothing. tcpdump captures packets before the firewall drops them. Don't waste time troubleshooting dnsmasq or AppArmor like me

maybe add a line in the README next to the firewalld note, since nftables is Arch's default and causes this identical "no lease" symptom
