### ISSUE TITLE
wifi not detecting

### ISSUE THREAD

**Issue by kart972** [lakinduakash/linux-wifi-hotspot#249]
**Describe the bug**
Manjaro gnome stoped detecting wifi adapter at all after using wifi hot spot

**To Reproduce**
Just use it one time on last version of mandatory gnome

**Desktop (please complete the following information):**
 - OS: manjaro
 - Version 21.2.6

**Comment by irisxerno** [comment]
i found that this can happen if you reboot the system before turning off the hotspot. when starting a hotspot, the script will add the wifi interface as unmanaged in NetworkManager.conf, and restores it back when stopping the hotspot. however, when rebooting, the unmanaged-devices line doesn't get removed and the script doesn't know to restore it to a version without it. 

this is quite a subtle issue and i think something should be done about it, so that users don't mysteriously lose their wifi if they happen to reboot the system.
