### ISSUE TITLE
Custom Login Page

### ISSUE THREAD

**Issue by sunnydiaz** [lakinduakash/linux-wifi-hotspot#94]
If an option can be added to use a custom login page for this hotspot. Example - Like hotels and guest houses. Or a guide directing how we can add that support.

**Comment by lakinduakash** [comment]
I think if that kind of topic does not match this repository. This project is for personal usage rather than that kind of purpose. However, you can have a fork and implement your logic and use it for your purpose. Also, I don't have an idea on how to implement this.  
Thank you for the suggestion anyway.
