### ISSUE TITLE
Use with `systemctl enable`?

### ISSUE THREAD

**Issue by ctjlewis** [lakinduakash/linux-wifi-hotspot#95]
In `create_ap`, we could run on startup with `systemctl enable create_ap`, but `systemctl enable wihotspot` does not work.

Does anyone know how to accomplish this? I will submit a PR for the README if so.

**Comment by lakinduakash** [comment]
`wihotspot` is referred to GUI. I think starting GUI as a service does not make sense. `create_ap` is the backend used by the GUI.

I think your problem is `create_ap` service does not use the configurations saved by the GUI. It is true. `create_ap` use different config file that is located at `/etc/create_ap.conf`. But GUI use this `/etc/wh.config` . The service file is at [here](https://github.com/ctjlewis/linux-wifi-hotspot/blob/master/src/scripts/create_ap.service). I think it can be changed to the new config file location. It is also required to copy the /etc/create_ap.conf` to `/etc/wh.config` when installing the software.

Thank you for reporting the issue :)
